sudo: required

language: generic

services:
  - docker

before_install:
  - echo "start creating an image with dockerfile"
  - docker build -t test -f Dockerfile.dev .

script:
  - docker run -e CI=TRUE test npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-west-1"
  app: "travisTestEB"
  env: "travistesteb-env"
  bucket_name: "elasticbeanstalk-us-west-1-138588601522"
  bucket_path: "travisTestEB"
  on:
    branch: master